### ISSUE TITLE
add attribute to disable OpenFile menu

### ISSUE THREAD

**Issue by prabirshrestha** [alekswebnet/pdfjs-viewer-element#18]
I load the pdf with src and would like to avoid others clicking Open File to open a menu.

**Comment by alekswebnet** [comment]
@prabirshrestha Since v2.5.0 you can use CSS to hide the open file button: https://github.com/alekswebnet/pdfjs-viewer-element#viewer-extra-styles

**Comment by prabirshrestha** [comment]
Verified this works.
