### ISSUE TITLE
Allow to set viewerCssTheme which allows setting dark, light or automatic mode.

### ISSUE THREAD

**Issue by prabirshrestha** [alekswebnet/pdfjs-viewer-element#20]
ref: https://github.com/mozilla/pdf.js/pull/12625

```js
const ViewerCssTheme = {
  AUTOMATIC: 0, // Default value.
  LIGHT: 1,
  DARK: 2,
};
```

Even better if we can pass options to the component or give us callback which allows to set the options.

**Comment by alekswebnet** [comment]
@prabirshrestha Implemented and will be available in the next release

**Comment by alekswebnet** [comment]
@prabirshrestha Since v2.5.0 you can use `viewer-css-theme` attribute to change viewer theme - `AUTOMATIC | LIGHT | DARK`

**Comment by prabirshrestha** [comment]
Don't think v2.5.0 is correctly released. Tried both with pnpm and npm and also verified in yarnkpkg site.

https://yarnpkg.com/package?q=pdfjs-viewer-element&name=pdfjs-viewer-element&version=2.5.0&file=%2Fdist%2Fpdfjs-viewer-element.js

```
  static get observedAttributes() {
    return ["src", "viewer-path", "locale", "page", "search", "phrase", "zoom", "pagemode", "text-layer"];
  }
```

I don't see the latest change.

```
['src', 'viewer-path', 'locale', 'page', 'search', 'phrase', 'zoom', 'pagemode', 'text-layer', 'viewer-css-theme', 'viewer-extra-styles']
```

**Comment by alekswebnet** [comment]
@prabirshrestha You are right, it was my mistake. Sorry for that 
The latest changes are available in the latest version: https://yarnpkg.com/package?q=pdfjs-viewer-element&name=pdfjs-viewer-element&version=2.5.2&file=%2Fdist%2Fpdfjs-viewer-element.js

**Comment by prabirshrestha** [comment]
It works now. Would be good to have this site updated too. https://alekswebnet.github.io/pdfjs-viewer-element/#api

**Comment by alekswebnet** [comment]
@prabirshrestha You are right, I will update it soon

**Comment by alekswebnet** [comment]
@prabirshrestha The website is updated. Thanks for sharing!

**Comment by prabirshrestha** [comment]
Thanks for the quick fix!
