### ISSUE TITLE
typings for eventbus differs from README

### ISSUE THREAD

**Issue by prabirshrestha** [alekswebnet/pdfjs-viewer-element#23]
README.md uses a function with callback. 

```javascript
viewerApp.eventBus.on('pagesloaded', () => {
  console.log('Viewer pages loaded')
})
```

while typings shows `eventBus: Record<string, any>;`.

https://github.com/alekswebnet/pdfjs-viewer-element/blob/732bc75b2557d778cc660defd96fb9dca10b3422/types/pdfjs-viewer-element.d.ts#L33C1-L33C39

if there is on how do I remove event listeners?

**Comment by alekswebnet** [comment]
@prabirshrestha Sorry for the late response. If this is still actual, you could try the `eventBus._off()` method:
https://github.com/mozilla/pdf.js/blob/6e46304357a7088a1b3b5d7a702d7618600af866/web/app.js#L2010

**Comment by alekswebnet** [comment]
Closed due inactivity
