### ISSUE TITLE
bit more documentation on using inside frameworks

### ISSUE THREAD

**Issue by andrisi** [alekswebnet/pdfjs-viewer-element#6]
Would love to see a bit more documentation on how to use inside framworks like Vue.

**Comment by alekswebnet** [comment]
Hi @andrisi, Nice tip! I will create a separate demo page on the documentation with examples for different frameworks. For which frameworks will you like to see a separate demo?

**Comment by andrisi** [comment]
I'm using Vue.js

**Comment by alekswebnet** [comment]
@andrisi I've added a new [page for demos](https://alekswebnet.github.io/pdfjs-viewer-element/#demo) and an example for Vue, hope this will be helpful
